
import { Inter } from "next/font/google";
import "./globals.css";
import Example from "./pagelayout/header/navigation/page";
import { Footer } from './pagelayout/footer/page';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Events",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
        <body className={inter.className}>
        <Example/>
        {children}
        <Footer/>
        </body>
      
    </html>
  );
}



